var namespacedepz__camera__sdk_1_1inference_1_1native__runtime =
[
    [ "_NativeNeuralRuntimeBase", "classdepz__camera__sdk_1_1inference_1_1native__runtime_1_1__NativeNeuralRuntimeBase.html", "classdepz__camera__sdk_1_1inference_1_1native__runtime_1_1__NativeNeuralRuntimeBase" ],
    [ "NativeStereoInferenceRuntime", "classdepz__camera__sdk_1_1inference_1_1native__runtime_1_1NativeStereoInferenceRuntime.html", "classdepz__camera__sdk_1_1inference_1_1native__runtime_1_1NativeStereoInferenceRuntime" ],
    [ "NativeMonoInferenceRuntime", "classdepz__camera__sdk_1_1inference_1_1native__runtime_1_1NativeMonoInferenceRuntime.html", "classdepz__camera__sdk_1_1inference_1_1native__runtime_1_1NativeMonoInferenceRuntime" ]
];